version: '3.8'

services:
  webflux:
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=test
      - POSTGRES_PORT=5432
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
    depends_on:
      - postgres
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123

